config:
  gcp:project: izakaya-488118
  gcp:region: us-central1
  izakaya:domain: dos.ivanoffdan.com
  izakaya:github-repo: dan-ivanov/izakaya
  izakaya:secret-key:
    secure: AAABAEQdn1sGh+niHlB60H7GUWBxifRMi+yRRPW1efOmjdsexem3RFXFW7SIAX2vW3CwmRFOz7hlS8o8Q0Au9a+BEivMyiBBSzOrqGPaAyADyM3qpLqy33v4Agn+XSQ5
  izakaya:fivetran-api-key:
    secure: AAABAPPZbK4CAzMbN63u0SRqkaqUiU73dIKpytI+LJ7sRsDIcCGYDtE7AA8VQSaO
  izakaya:fivetran-api-secret:
    secure: AAABAHaJpc5vF67oEUlQCkHuDTLyl79gVAREyoN97si1j/kzvQ45gkIWrsNTcH+/fscW4D3MktuMUdMWv4rdXg==
  izakaya:fivetran-group-id:
    secure: AAABADXJ2eg4sLEzxntSOoFqPMW8WXj125lpKt8pvWDW+/aZoNYKlpesiUyzFOY=
  izakaya:anthropic-api-key:
    secure: AAABAG+4Y8rUKRh2w1XqXfSlQj86EFogPX+Cz0XcSGqMj2B6v4KVAok+pAnjEHRkkhF8wZpbzxZH1mcYe8/Gxug6KC02QL34rlHenliwB6RDTOypyU4TZPAo+6jXHefV5msMCKgen7xwPduIlGWLlMTx4aYRRaJ1eNjz4xJxDXMzsMxzlajQrSrzzIM=
