"""add static_value to mappings

Revision ID: 25091e364040
Revises: 3629c0126412
Create Date: 2026-02-21 16:11:59.482411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25091e364040'
down_revision: Union[str, None] = '3629c0126412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings', sa.Column('static_value', sa.String(length=500), nullable=True))
    op.alter_column('mappings', 'source_column',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mappings', 'source_column',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('mappings', 'static_value')
    # ### end Alembic commands ###
