"""add_confidence_to_mappings

Revision ID: 882b91ad83d2
Revises: b2c3d4e5f6a7
Create Date: 2026-02-25 17:17:29.175557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '882b91ad83d2'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mappings', sa.Column('confidence', sa.Float(), nullable=True))
    op.add_column('mappings', sa.Column('reasoning', sa.String(length=1000), nullable=True))
    op.add_column('mappings', sa.Column('ai_suggested', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mappings', 'ai_suggested')
    op.drop_column('mappings', 'reasoning')
    op.drop_column('mappings', 'confidence')
    # ### end Alembic commands ###
