"""add service and setup_state to connectors

Revision ID: 9e200617814a
Revises: bec0febc32f0
Create Date: 2026-02-21 14:21:24.554746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e200617814a'
down_revision: Union[str, None] = 'bec0febc32f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('service', sa.String(length=100), nullable=False, server_default=''))
    op.add_column('connectors', sa.Column('setup_state', sa.String(length=50), nullable=False, server_default='incomplete'))
    op.add_column('connectors', sa.Column('sync_state', sa.String(length=50), nullable=True))
    op.alter_column('connectors', 'fivetran_connector_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('connectors', 'fivetran_connector_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('connectors', 'sync_state')
    op.drop_column('connectors', 'setup_state')
    op.drop_column('connectors', 'service')
    # ### end Alembic commands ###
