"""add ai_suggested and confidence to label_rules

Revision ID: dbf47393a748
Revises: eb6acd09f2df
Create Date: 2026-02-21 17:17:31.718574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbf47393a748'
down_revision: Union[str, None] = 'eb6acd09f2df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label_rules', sa.Column('ai_suggested', sa.Boolean(), nullable=True))
    op.add_column('label_rules', sa.Column('confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label_rules', 'confidence')
    op.drop_column('label_rules', 'ai_suggested')
    # ### end Alembic commands ###
