"""add_fivetran_sync_details_to_connectors

Revision ID: eb6acd09f2df
Revises: 25091e364040
Create Date: 2026-02-21 16:42:54.029313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6acd09f2df'
down_revision: Union[str, None] = '25091e364040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connectors', sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('connectors', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('connectors', sa.Column('sync_frequency', sa.Integer(), nullable=True))
    op.add_column('connectors', sa.Column('schedule_type', sa.String(length=50), nullable=True))
    op.add_column('connectors', sa.Column('paused', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('connectors', sa.Column('daily_sync_time', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connectors', 'daily_sync_time')
    op.drop_column('connectors', 'paused')
    op.drop_column('connectors', 'schedule_type')
    op.drop_column('connectors', 'sync_frequency')
    op.drop_column('connectors', 'failed_at')
    op.drop_column('connectors', 'succeeded_at')
    # ### end Alembic commands ###
