"""add_mappings_accepted

Revision ID: f0995f8d3a92
Revises: 882b91ad83d2
Create Date: 2026-02-25 17:45:07.576588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0995f8d3a92'
down_revision: Union[str, None] = '882b91ad83d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_sources', sa.Column('mappings_accepted', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_sources', 'mappings_accepted')
    # ### end Alembic commands ###
