name: Dagster Cloud Deploy
on:
  push:
    branches: [main]
    paths: [pipeline/**]
  pull_request:
    types: [opened, synchronize, reopened, closed]
    paths: [pipeline/**]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}/deploy
  cancel-in-progress: true

env:
  DAGSTER_CLOUD_API_TOKEN: ${{ secrets.DAGSTER_CLOUD_API_TOKEN }}
  DAGSTER_CLOUD_ORGANIZATION: ${{ secrets.DAGSTER_CLOUD_ORGANIZATION }}
  DAGSTER_CLOUD_YAML_PATH: .
  DAGSTER_CLOUD_FILE: dagster_cloud.yaml
  ENABLE_FAST_DEPLOYS: "true"
  PYTHON_VERSION: "3.12"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  dagster_cloud_deploy:
    name: Dagster Serverless Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Prerun Checks
        id: prerun
        uses: dagster-io/dagster-cloud-action/actions/utils/prerun@v1.11.9

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref || github.ref }}

      - name: Validate configuration
        id: ci-validate
        if: steps.prerun.outputs.result != 'skip'
        uses: dagster-io/dagster-cloud-action/actions/utils/dagster-cloud-cli@v1.11.9
        with:
          command: "ci check --project-dir ${{ env.DAGSTER_CLOUD_YAML_PATH }} --dagster-cloud-yaml-path ${{ env.DAGSTER_CLOUD_FILE }}"

      - name: Initialize build session
        id: ci-init
        if: steps.prerun.outputs.result != 'skip'
        uses: dagster-io/dagster-cloud-action/actions/utils/ci-init@v1.11.9
        with:
          project_dir: ${{ env.DAGSTER_CLOUD_YAML_PATH }}
          dagster_cloud_yaml_path: ${{ env.DAGSTER_CLOUD_FILE }}
          deployment: prod

      - name: Set up Python
        if: steps.prerun.outputs.result == 'pex-deploy'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Run PEX build
        id: run-pex-build
        if: steps.prerun.outputs.result == 'pex-deploy'
        uses: dagster-io/dagster-cloud-action/actions/utils/dagster-cloud-cli@v1.11.9
        with:
          command: "ci build --build-strategy=python-executable --python-version ${{ env.PYTHON_VERSION }} --pex-deps-cache-from='${{ github.repository }}' --pex-deps-cache-to='${{ github.repository }}'"

      - name: Deploy to Dagster Cloud
        id: ci-deploy
        if: steps.prerun.outputs.result != 'skip'
        uses: dagster-io/dagster-cloud-action/actions/utils/dagster-cloud-cli@v1.11.9
        with:
          command: "ci deploy"

      - name: Update PR comment
        id: ci-notify
        if: steps.prerun.outputs.result != 'skip'
        uses: dagster-io/dagster-cloud-action/actions/utils/dagster-cloud-cli@v1.11.9
        with:
          command: "ci notify --project-dir=${{ env.DAGSTER_CLOUD_YAML_PATH }}"

      - name: Summary
        id: ci-summary
        if: steps.prerun.outputs.result != 'skip'
        uses: dagster-io/dagster-cloud-action/actions/utils/dagster-cloud-cli@v1.11.9
        with:
          command: "ci status --output-format=markdown >> $GITHUB_STEP_SUMMARY"
